# CI workflow runs linting and tests across multiple Python versions
# Using GitHub Actions matrix strategy to ensure compatibility.
#
# Steps:
# 1. Checkout repository source.
# 2. Set up Python interpreter for each version in matrix.
# 3. Install the package in editable mode with pip.
# 4. Run Ruff for style checks.
# 5. Execute pytest to validate functionality.
#
# The workflow triggers on pushes and pull requests targeting the main branch.
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff pytest

      - name: Run Ruff
        run: ruff check .

      - name: Run tests
        run: pytest -q
